export const CREATE_FOLDER = 'CREATE_FOLDER';
export const ADD_FOLDERS = 'ADD_FOLDERS';
export const SET_LOADING = 'SET_LOADING';
export const CHANGE_FOLDER = 'CHANGE_FOLDER';
export const CREATE_FILE = 'CREATE_FILE';
export const ADD_FILES = 'ADD_FILES';
export const SET_FILE_DATA = 'SET_FILE_DATA';
export const DELETE_FILE = 'DELETE_FILE'; // Add this line
export const DELETE_FOLDER = 'DELETE_FOLDER'; // Add this line
export const UPDATE_ITEM_NAME = "UPDATE_ITEM_NAME";